breeding=false
dragging=true
ie_interactions=true
ie_throwing=true
cursor_data=true
mascot_limit=512
ie_throw_policy=3
allow_dismiss_animations=true
per_mascot_interactions=true
overlay_layer=3
tablets_enabled=true
mascot_scale=1.500000
