# Config Root for Hyprland (Main Branch)
#   Source config files are stored in ~/.config/hypr/hyprsource/...
$HYPR_DIR= ~/.config/hypr/hyprsource/
source = $HOME/.cache/wal/colors-hyprland.conf

source = $HYPR_DIR/defaults.conf
source = $HYPR_DIR/monitors.conf
source = $HYPR_DIR/env_vars.conf
source = $HYPR_DIR/startup_exec.conf
source = $HYPR_DIR/ui_tuner.conf
source = $HYPR_DIR/win_rules.conf
source = $HYPR_DIR/key_binds.conf
source = $HYPR_DIR/plugins.conf

# Enable this if on a laptop
source = $HYPR_DIR/lappy_rules.conf

# Notes below (Things to implement)
#   Add a switch for light-dark mode              			 [Done]
#   Check for performance issues & memory leaks     			 [Done]
#   Add seperate configuration for laptops          			 [Done]
#   Implement Special Workspace to mimic minimise fnctionality           [Pending]
#   Add ALT-TAB functionality                                            [Done]
