# Custom pywal theme generation for snappy-switcher (alt-tab window switcher of hyprland)

[colors]
background = #151026
card_bg = #3F8FBF
card_selected = #635f74
border_color = #56A6B6
text_color = #c4c3c8
subtext_color = #c4c3c8
