#  ┳┳┓┏┓┳┓┳┏┳┓┏┓┳┓┏┓
#  ┃┃┃┃┃┃┃┃ ┃ ┃┃┣┫┗┓
#  ┛ ┗┗┛┛┗┻ ┻ ┗┛┛┗┗┛
# WARN: Bit-depth doesn't works on external monitors through HDMI-A-1 for some reason

# ACER 14.1 IPS Panel (laptop_screen)
monitor = eDP-1, highres, auto, 1.15, transform, 0, bitdepth, 10, cm, srgb

# ACER 24 IPS Monitor (ext_monitor)
monitor = HDMI-A-1, highres, auto, 1.0, transform, 0, bitdepth, 10, cm, srgb

# Disable laptop screen
monitor = eDP-1, disable


#  ┓ ┏┏┓┳┓┓┏┓┏┓┏┓┏┓┏┓┏┓┏┓
#  ┃┃┃┃┃┣┫┃┫ ┗┓┃┃┣┫┃ ┣ ┗┓
#  ┗┻┛┗┛┛┗┛┗┛┗┛┣┛┛┗┗┛┗┛┗┛
# INFO: Assigning monitors to respective workspaces
workspace = 1, monitor:eDP-1
workspace = 2, monitor:HDMI-A-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:HDMI-A-1
workspace = 5, monitor:eDP-1
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:eDP-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:eDP-1
workspace = 10, monitor:HDMI-A-1
