#     __  __ ____   ______                         
#    / / / //  _/  /_  __/__  __ ____   ___   _____
#   / / / / / /     / /  / / / // __ \ / _ \ / ___/
#  / /_/ /_/ /     / /  / /_/ // / / //  __// /    
#  \____//___/    /_/   \__,_//_/ /_/ \___//_/     
#                                                  



#  ┏┓┏┓┳┓┏┓┳┓┏┓┓ 
#  ┃┓┣ ┃┃┣ ┣┫┣┫┃ 
#  ┗┛┗┛┛┗┗┛┛┗┛┗┗┛
#                
general {
    gaps_in = 10
    gaps_out = 20
    border_size = 2
    layout = dwindle

# blue-green gradient
    col.active_border = $color6
    col.inactive_border = $color2
#    col.active_border = rgba(184,212,239,1) rgba(212,197,243,1)
#    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
#    col.inactive_border = rgba(14,15,21,1.0)
}


#  ┳┓┏┓┏┓┏┓┳┓┏┓┏┳┓┳┏┓┳┓
#  ┃┃┣ ┃ ┃┃┣┫┣┫ ┃ ┃┃┃┃┃
#  ┻┛┗┛┗┛┗┛┛┗┛┗ ┻ ┻┗┛┛┗
#                      
decoration {
    rounding = 8
    rounding_power = 5
    blur {
        enabled = true
        size = 10
        passes = 4
        new_optimizations = true
        ignore_opacity=true
        xray = true
        brightness = 1.2
	    noise = 0.1
	    special = true
	    popups = true
	    input_methods = true
    }

    shadow {
        enabled = false
        range = 10
        render_power = 10
        color = rgba(1a1a1aee)

    }

    active_opacity = 0.85
    inactive_opacity = 0.9
    fullscreen_opacity = 1
}



#  ┏┓┳┓┳┳┳┓┏┓┏┳┓┳┏┓┳┓┏┓
#  ┣┫┃┃┃┃┃┃┣┫ ┃ ┃┃┃┃┃┗┓
#  ┛┗┛┗┻┛ ┗┛┗ ┻ ┻┗┛┛┗┗┛
#                      
animations {
    enabled = true

    bezier = easeOutExpo, 0.29, 0.97, 0.39, 0.7
    bezier = easeOutQuad, 0.5, 1, 0.89, 1
    bezier = zoink, 0.13, 0.99, 0.29, 1.1
    bezier = overshot, 0.05, 0.9, 0.1, 1.1 # effect similar to zoink

    # animation = windowsIn, 1, 4, zoink, popin 80%
    animation = windowsIn, 1, 4, zoink, gnomed
    animation = windowsOut, 1, 7, zoink, gnomed

    animation = border, 1, 10, default
    animation = borderangle, 1, 8, zoink, loop
    
    animation = fade, 1, 7, zoink
    animation = workspaces, 1, 4, zoink, slidefadevert 35%
    animation = layers, 1, 5, zoink, popin 50%
}
