#!/bin/bash

MODE=$1
# Incorrect input - Show help information
if [[ "$MODE" != "light" && "$MODE" != "dark" ]]; then
    echo "Usage: $0 [light|dark]"
    exit 1
fi

# Declare directory variables
HOME=/home/$(whoami)
WALLPAPER="$(grep "wallpaper =" ~/.config/waypaper/config.ini | cut -d ' ' -f3)"
WALLPAPER="${WALLPAPER/#\~/$HOME}"
ENV_DIR="$HOME/.config/hypr/hyprsource/env_vars.conf"
CONFIG_ULAUNCHER="$HOME/.config/ulauncher/settings.json"

echo "Switching to $MODE mode..."

# Update colorscheme
if [[ "$MODE" == "light" ]]; then
    wal -ni "$WALLPAPER" -lt
elif [[ "$MODE" == "dark" ]]; then
    wal -ni "$WALLPAPER"
fi

# Determine accent color
COLOR="$(grep "color9" ~/.cache/wal/colors.css | cut -d '#' -f2)"
COLOR="${COLOR%;}" # HEX Code of the color
echo "Acquired color: $COLOR"
accent=$(python $HOME/.scripts/color-extract.py $COLOR)
echo "Accent color: $accent"

if [ "$MODE" == "dark" ]; then
    GTK_THEME="WhiteSur-Light"
    COLOR_SCHEME="prefer-dark"
    ULAUNCHER_THEME="darkblue-ice"
    WAYBAR_STYLE=$HOME/.config/waybar/style-theme/style-dark.css
    ACCENT="$accent:dark"
else
    GTK_THEME="WhiteSur-Light"
    COLOR_SCHEME="prefer-light"
    ULAUNCHER_THEME="light"
    WAYBAR_STYLE=$HOME/.config/waybar/style-theme/style-light.css
    ACCENT="$accent"
fi

# Switch waybar stylesheet
cp "$WAYBAR_STYLE" "$HOME/.config/waybar/style.css"
echo "Swapped waybar stylesheet for $MODE mode."

# Apply GSettings (for running GTK apps)
gsettings set org.gnome.desktop.interface gtk-theme "$GTK_THEME-$ACCENT" 2>/dev/null
gsettings set org.gnome.desktop.interface color-scheme "$COLOR_SCHEME" 2>/dev/null
sed -i "s/\(env = GTK_THEME,\).*/\1$GTK_THEME-$ACCENT/" "$ENV_DIR"
echo "GTK Theme switched to $GTK_THEME-$ACCENT. Restart for changes!"

# Update Ulauncher theme
sed -i "s/\"theme-name\": \".*\"/\"theme-name\": \"$ULAUNCHER_THEME\"/" "$CONFIG_ULAUNCHER"
pkill ulauncher
ulauncher --no-window-shadow & disown
echo "Ulauncher theme updated to $ULAUNCHER_THEME"